### ISSUE TITLE
How to resolve after css is loaded

### ISSUE THREAD

**Issue by markcellus** [markcellus/dynamic-import#6]
Opening a new issue to discuss @kapilpipaliya's comment

> when i load css. it seems it returns immediately. how to resolve it after loaded?

@kapilpipaliya the css loading isn't async yet but are you running into issues as a result? If so, what are they so I can help. 

FYI: I have to admit that I haven't been as active on updating this repo because we now have [`import()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import).

**Comment by kapilpipaliya** [comment]
I want to be sure that my css is loaded before rendering dom. if component is rendered before css is actually loaded, it create some bad flush effectes.

**Comment by mkay581** [comment]
Yes, the flush effect can be fixed by ensuring that the CSS is loaded before the component is rendered. Are you sure this is happening?

**Comment by mkay581** [comment]
Going to close this due to inactivity. Feel free to continue discussion if there is issue.
